### ISSUE TITLE
As a ticket dashboard developer I want to publish this application on the Open Data Hub infrastructure so that the team can start testing it

### ISSUE THREAD

**Issue by clezag** [noi-techpark/opendatahub-tickets-dashboard#1]
- [x] Dockerize
- [x] Setup CI/CD
- [x] Setup DNS

**Comment by clezag** [comment]
There's a few things to do, to bring this in line with our internal standards, so that we can put it into testing (I'd recommend doing them in this order):

1. for the `.env` file, we usually keep a `.env.example` file in our repos, that serves as an example for the `.env`, without any secrets, so that i can be pushed to the repo.
2. We don't develop with local dependencies, but with containers. So in the main directory there should be a `docker-compose.yml` which, using the `.env` file builds and launches the application locally for development
3. for deployment, the application has to be dockerized. In every repo we have a `infrastructure` folder, which contains among other things the Dockerfile, ansible scripts, and compose files. You can refer to [this (python)](https://github.com/noi-techpark/sustainability-assessment-tool) or [this (js)](https://github.com/noi-techpark/com.opendatahub.api.gtfs) repo as a starting point. Copy the whole infrastructure folder, and then customize the `Dockerfile` for your application, the rest should already be good.
4. The testing, build and deployment are automated via github actions on every repo push. For this, copy the `.github/workflows` folder from [here](https://github.com/noi-techpark/com.opendatahub.api.gtfs/blob/main/.github/workflows/) and customize them. Swapping out the project names and setting your own specific `.env` variables should be all you need

Let me know if you need help with any specific step.

**Comment by lukmay** [comment]
Thank you, @clezag, for the excellent explanation.
Everything is clear so far.

I’ll begin working on it, and if I need any help, I’ll reach out to you.
